[project]
name = "gil-analyze"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "psutil>=7.0.0",
    "pyinstrument>=5.0.1",
    "viztracer>=1.0.4",
]
